#!/usr/bin/python3
"""This Module Factorize as many numbers as possible into a product
of two smaller numbers."""

from sys import argv


def factorize(x):
    """"Print a concise breakdown of an integer > 1,
    showing its prime factors and multiplicities."""
    i = 2

    if x < 2:
        return
    print()
    print(x, "<- x-bef")
    while x % i:
        i += 1
    print("{:.0f}={:.0f}*{:.0f}".format(x, x / i, i))
    print(x, "<- x-aft")
    print()


if len(argv) != 2:
    exit()

try:
    with open(argv[1]) as f:
        line = f.readline()

        while line != "":
            x = int(line.split('\n')[0])
            factorize(x)
            line = f.readline()
ecept:
    pass
