#!/usr/bin/env python3
""" Factorize as many numbers as possible into
a product of two smaller numbers. """


from sys import argv
from math import sqrt


def read_file(fname):
    """
    Reads from a file and adds the contents to an array.
    """
    with open(fname, "r", encoding="utf-8") as f:
        lines = f.readlines()
    num = []
    for line in lines:
        num.append(int(line))
    return num


def findFactors(x):
    """
    Find and display the factors of a given number.
    """
    for i in range(1, x):
        if x == ((x // i) * i):
            print("{}={}*{}".format(x, (x // i), i))
            break


def factorize_list(lst):
    """
    Factorize each number in the given list.
    """
    for i in lst:
        findFactors(i)


if len(argv) == 2:
    factorize_list(read_file(argv[1]))
