#!/usr/bin/env python3

def factorize_numbers(filename):
    with open(filename, 'r') as f:
        for line in f:
            num = int(line)
            factors = find_factors(num)
            print("{}={}*{}".format(num, factors[0], factors[1]))


def find_factors(x):
    for i in range(2, x):
        if x % i == 0:
            return (i, int(x / i))


if __name__ == "__main__":
    import sys

    if len(sys.argv) != 2:
        raise SyntaxError("[BAD-USAGE]: Expected only one argument")

    factorize_numbers(sys.argv[1])
