#!/usr/bin/python3
from sys import argv

with open(argv[1]) as file:
    for line in file:
        n = int(line)
        print("{:d}=".format(n), end="")
        if n % 2 == 0:
            print("{}*2".format(n//2))
            continue
        for i in range(3, n, 2):
            if n % i == 0:
                fact = n//i
                for j in range(3, fact, 2):
                    if fact % j == 0 or i % j == 0:
                        break
                print("{}*{}".format(fact, i))
                break
